# Generated by Django 5.0.6 on 2026-04-28 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organisations', '0002_organisationmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='organisations.organisation'),
        ),
    ]
