# Generated by Django 5.0.6 on 2026-04-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_current_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('candidate', 'Candidate')], default='admin', max_length=20),
        ),
    ]
