# Generated by Django 5.0.6 on 2026-05-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('candidate', 'Candidate')], default='candidate', max_length=20),
        ),
    ]
