# Generated by Django 5.0.6 on 2026-03-20 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='auto_submit_on_violation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='violation_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='total_violations',
            field=models.IntegerField(default=0),
        ),
    ]
