# Generated by Django 5.0.6 on 2026-03-22 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_auto_submit_on_violation_exam_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
