# Generated by Django 5.0.6 on 2026-03-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examattempt_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
