# Generated by Django 5.0.6 on 2026-04-28 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_exam_is_published'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='organisations.organisation'),
        ),
    ]
