# Generated by Django 5.0.6 on 2026-04-28 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_organisation'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='organisations.organisation'),
        ),
    ]
