# Generated by Django 5.0.6 on 2026-05-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_remove_examattempt_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattempt',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
    ]
