# Generated by Django 5.0.6 on 2026-03-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='violation',
            name='severity',
            field=models.IntegerField(default=1),
        ),
    ]
