# Generated by Django 5.0.6 on 2026-04-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_screenshot_flagged_violation_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to='screenshots/'),
        ),
    ]
