# Generated by Django 5.0.6 on 2026-04-29 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisationmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(default='candidate', max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='organisations.organisation')),
            ],
        ),
    ]
