# Generated by Django 5.0.6 on 2026-05-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_organisationinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationinvite',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisationinvite',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
