# Generated by Django 5.0.6 on 2026-05-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_organisationinvite_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='max_admins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organisation',
            name='max_invigilators',
            field=models.IntegerField(default=0),
        ),
    ]
